//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splitey.Api.Resources.Payment.Settlement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Splitey.Api.Resources.Payment.Settlement.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    S.&quot;From&quot; AS &quot;From&quot;,
        ///    S.&quot;To&quot; AS &quot;To&quot;,
        ///    SUM(S.&quot;Value&quot;) AS &quot;Balance&quot;
        ///FROM (
        ///    SELECT
        ///        TPC.&quot;SettlementMemberId&quot; AS &quot;From&quot;,
        ///        T.&quot;PaidBy&quot; AS &quot;To&quot;,
        ///        TPC.&quot;Amount&quot; * TP.&quot;Price&quot; AS &quot;Value&quot;
        ///    FROM &quot;payment&quot;.&quot;Transfer&quot; T
        ///        JOIN &quot;payment&quot;.&quot;TransferProduct&quot; TP 
        ///            ON T.&quot;Id&quot; = TP.&quot;PaymentId&quot;
        ///        JOIN &quot;payment&quot;.&quot;TransferProductContribution&quot; TPC 
        ///            ON TP.&quot;Id&quot; = TPC.&quot;TransferProductId&quot;
        ///    WHERE 
        ///        T.&quot;Type&quot; = &apos;RESTAURANT&apos; AND 
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetArrangement {
            get {
                return ResourceManager.GetString("GetArrangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    &quot;Id&quot;,
        ///    &quot;UserId&quot;,
        ///    &quot;PersonId&quot;
        ///FROM &quot;payment&quot;.&quot;SettlementMember&quot;.
        /// </summary>
        internal static string GetMembers {
            get {
                return ResourceManager.GetString("GetMembers", resourceCulture);
            }
        }
    }
}
